export const SourceList = [

    { name: "3D Printing Progress" },
    { name: "4th Annual Congress and Expo on Biofuels and Bioenergy April 27-28 2017 Dubai UAE" },
    { name: "About Best Binary Options Strategy" },
    { name: "Abq" },
    { name: "Activist Post" },
    { name: "Adam Curry" },
    { name: "African Arguments" },
    { name: "African Development Bank" },
    { name: "agriworldsa" },
    { name: "AgWeb - The Home Page of Agriculture" },
    { name: "AHDB" },
    { name: "Aljazeera.com" },
    { name: "AllAfrica" },
    { name: "allianzglobalinvestors" },
    { name: "AMERICAN COUNCIL ON SCIENCE AND HEALTH" },
    { name: "amundi" },
    { name: "arabellaadvisors" },
    { name: "Arangkada Philippines" },
    { name: "aswm" },
    { name: "Atlantic Council " },
    { name: "atradius" },
    { name: "Australian Government" },
    { name: "Australian Government Department of Defence" },
    { name: "Avi Melamed" },
    { name: "Azonano" },
    { name: "bankofcanada" },
    { name: "bankofengland" },
    { name: "BBC News Technology" },
    { name: "Bearnobull" },
    { name: "Before It's News | Alternative News | UFO | Beyond Science | True News| Prophecy News | People Powered News" },
    { name: "betterenergy" },
    { name: "Biofuels Digest" },
    { name: "biologicaldiversity" },
    { name: "biomassmagazine" },
    { name: "Bloomberg Business" },
    { name: "Bloomberg New Energy Finance" },
    { name: "Blue and Green Tomorrow" },
    { name: "BorneoPost Online" },
    { name: "briandcolwell" },
    { name: "Brookings Institute" },
    { name: "Business Green" },
    { name: "Business Insider" },
    { name: "Business Standard" },
    { name: "Business Wire" },
    { name: "CAFrackFacts" },
    { name: "CAJ News Africa" },
    { name: "Canadian Biomass" },
    { name: "Carbon Brief" },
    { name: "cargill" },
    { name: "Cars.co.za" },
    { name: "CBO" },
    { name: "CCN: Financial Bitcoin & Cryptocurrency News" },
    { name: "CDC" },
    { name: "Channel News Asia" },
    { name: "Cii Radio" },
    { name: "CIO" },
    { name: "Citibank" },
    { name: "CleanTechnica" },
    { name: "clientadvisoryservices" },
    { name: "Climate Change News" },
    { name: "Climate News Network" },
    { name: "cloudfront" },
    { name: "CNBC " },
    { name: "CNNMoney" },
    { name: "Common Dreams" },
    { name: "conferenceseries" },
    { name: "controleng" },
    { name: "Convenience Store Decisions" },
    { name: "Cornell University" },
    { name: "Countries.com Global Content" },
    { name: "cpzulia" },
    { name: "creamermedia" },
    { name: "Critical Threats" },
    { name: "CSIS" },
    { name: "Cushman & Wakefield" },
    { name: "Cushman & Wakefield Blog" },
    { name: "dailyquiddity" },
    { name: "dailytexanonline" },
    { name: "Days Of Year" },
    { name: "Digitalist Magazine" },
    { name: "djsresearch" },
    { name: "DOE EIA 2013 Energy Conference" },
    { name: "dpaq" },
    { name: "Drill or drop?" },
    { name: "Drydock Magazine" },
    { name: "DW.COM" },
    { name: "ebrd" },
    { name: "ecesr" },
    { name: "ECFR" },
    { name: "Eco-Business.com" },
    { name: "economy" },
    { name: "Edge and Odds" },
    { name: "edie.net" },
    { name: "EE News" },
    { name: "EGYPS" },
    { name: "EIA" },
    { name: "EIU" },
    { name: "Elsevier" },
    { name: "Embedded Computing Design" },
    { name: "energy news cyprus" },
    { name: "Energy Tomorrow" },
    { name: "Energy.gov Website" },
    { name: "energyglobal" },
    { name: "Engineering News" },
    { name: "Environmental Leader" },
    { name: "environmentalpeacebuilding" },
    { name: "EPA" },
    { name: "EPS News" },
    { name: "ESPAS" },
    { name: "ETEnergyworld.com" },
    { name: "ethicalconsumer" },
    { name: "ethicalmarkets" },
    { name: "Euler Hermes" },
    { name: "Eurasia Group" },
    { name: "Euromoney" },
    { name: "Europa" },
    { name: "Europe in My Region" },
    { name: "European Central Bank" },
    { name: "European Council" },
    { name: "European Environment Agency" },
    { name: "europeanclimate" },
    { name: "EV Obsession" },
    { name: "EY" },
    { name: "Face2face Africa" },
    { name: "FAO" },
    { name: "farms" },
    { name: "Farms.com" },
    { name: "FashionNetwork.com" },
    { name: "Fast Co-Exist" },
    { name: "Fews Net" },
    { name: "Finance Magnates" },
    { name: "Fitch" },
    { name: "FoodQualityNews.com" },
    { name: "Foreign Policy" },
    { name: "Fox Business" },
    { name: "Freedonia" },
    { name: "Freenewspos" },
    { name: "friday-thinking" },
    { name: "Future Earth" },
    { name: "Future in Focus" },
    { name: "Future Market Insights" },
    { name: "Future Timeline" },
    { name: "FutureinFocus" },
    { name: "Futureseek Link Digest" },
    { name: "Futurity" },
    { name: "FX Empire" },
    { name: "g7g20" },
    { name: "Gartner" },
    { name: "Gas 2" },
    { name: "gasstrategies" },
    { name: "GE Reports" },
    { name: "Gii Research" },
    { name: "Gizmodo Australia" },
    { name: "Global Information Inc" },
    { name: "Global Money Trends" },
    { name: "Global Money Trends Magazine" },
    { name: "globalfueleconomy" },
    { name: "globalizationpartners" },
    { name: "GlobalMeatNews.com" },
    { name: "globalmoneytrends" },
    { name: "globalr2p" },
    { name: "Government of Ireland" },
    { name: "GreenBiz" },
    { name: "greenerearthnews" },
    { name: "Guardian" },
    { name: "Guardian Sustainable Business" },
    { name: "Guarini Center" },
    { name: "Handelsblatt Global Edition" },
    { name: "Hardin Tibbs" },
    { name: "HBR" },
    { name: "Hospitality Trends" },
    { name: "Huffington Post" },
    { name: "iamericas" },
    { name: "IASTOPPERS" },
    { name: "IBEF" },
    { name: "ID TECH INDEX" },
    { name: "idc-community" },
    { name: "IEA" },
    { name: "IEA.org" },
    { name: "IER" },
    { name: "IFT" },
    { name: "IHS Engineering 360" },
    { name: "ihsmarkit" },
    { name: "IISS" },
    { name: "Imeche" },
    { name: "IMF" },
    { name: "iMFdirect - The IMF Blog" },
    { name: "Industrial Control Security" },
    { name: "Industry Week" },
    { name: "Informed Choice Chartered Financial Planners in Cranleigh" },
    { name: "Infracircle" },
    { name: "Innovaro" },
    { name: "Innovate UK" },
    { name: "Innovations Report" },
    { name: "inputsmonitor" },
    { name: "INSEAD Knowledge" },
    { name: "Inside Climate News" },
    { name: "Institutional Investor" },
    { name: "Insurance Journal" },
    { name: "Interior Design" },
    { name: "International Banker" },
    { name: "International Business Times" },
    { name: "International Monetary Fund (IMF)" },
    { name: "Investopedia" },
    { name: "IRENA" },
    { name: "IRENA newsroom" },
    { name: "ISA" },
    { name: "Jachin Capital" },
    { name: "JD Supra" },
    { name: "jeita" },
    { name: "Justmeans" },
    { name: "Khaleej Times" },
    { name: "khorreports-palmoil" },
    { name: "knomad" },
    { name: "Koenig Investment Advisory" },
    { name: "Lawfare" },
    { name: "Le·gal In·sur·rec·tion" },
    { name: "LiveMint" },
    { name: "LNG" },
    { name: "maltawinds.com" },
    { name: "Manufacturing Operations Technology Viewpoints" },
    { name: "MAPI" },
    { name: "Maplecroft" },
    { name: "marketrealist" },
    { name: "Mast" },
    { name: "McKinsey & Company" },
    { name: "McKinsey Quarterly" },
    { name: "Media Center " },
    { name: "MENA-Forum" },
    { name: "metalprices" },
    { name: "Middle East Eye" },
    { name: "Middle East Online" },
    { name: "Mind Commerce" },
    { name: "MIT Sloan Management Review" },
    { name: "MIT Technology Review" },
    { name: "Motor Magazine" },
    { name: "MRC" },
    { name: "murc" },
    { name: "Nanotechnology Innovation" },
    { name: "Nation of Change" },
    { name: "National Geographic Society (blogs)" },
    { name: "Nature" },
    { name: "nbk" },
    { name: "nbp" },
    { name: "NDTV" },
    { name: "Neon Nettle" },
    { name: "New Security Beat" },
    { name: "News" },
    { name: "News.com" },
    { name: "newscientist" },
    { name: "Newsletter" },
    { name: "Newsweek" },
    { name: "nextbigfuture" },
    { name: "Nexus Conference" },
    { name: "njc-cnm" },
    { name: "No 2 Nuclear Power" },
    { name: "NWF" },
    { name: "NY Times" },
    { name: "Ocean Acidification" },
    { name: "OEM/Lube News" },
    { name: "ogauthority" },
    { name: "Oil and Gas Journal" },
    { name: "oilprice.com" },
    { name: "oilvoice" },
    { name: "OklahomaMinerals.com" },
    { name: "OMFIF" },
    { name: "OPEC" },
    { name: "Oxfam" },
    { name: "PDQFX news" },
    { name: "Peak Prosperity" },
    { name: "Phys Org" },
    { name: "Physics World" },
    { name: "Pickens Plan" },
    { name: "Planetizen" },
    { name: "Planetsave " },
    { name: "platts" },
    { name: "Politico" },
    { name: "polymerspaintcolourjournal" },
    { name: "portfolioticker" },
    { name: "PR Newswire" },
    { name: "Predictive Analytics Times" },
    { name: "PriceWaterhouseCoopers" },
    { name: "Project Syndicate" },
    { name: "Prospects for Development" },
    { name: "prsync" },
    { name: "PwC" },
    { name: "Quartz" },
    { name: "ReadWrite" },
    { name: "Real Estate Professional" },
    { name: "Renewable Energy World" },
    { name: "Resilience" },
    { name: "Resources for the Future" },
    { name: "Reuters" },
    { name: "Rigzone" },
    { name: "RiskMap 2017" },
    { name: "Robothub" },
    { name: "RUSI" },
    { name: "Russia Beyond The Headlines" },
    { name: "saltlakecityheadlines" },
    { name: "satprnews" },
    { name: "savepassamaquoddybay" },
    { name: "SBWire" },
    { name: "Scania Group" },
    { name: "Science Daily" },
    { name: "Science News" },
    { name: "Scientific American" },
    { name: "Seeking Alpha" },
    { name: "Shenandoah" },
    { name: "SlideShare" },
    { name: "Slinking Toward Retirement" },
    { name: "Smart Grid Observer" },
    { name: "Society of Motor Manufacturers and Traders (SMMT)" },
    { name: "South China Morning Post" },
    { name: "South Sudan News Agency" },
    { name: "South World" },
    { name: "Sputnik News" },
    { name: "Stanford News" },
    { name: "Star Tribune" },
    { name: "Strategy & Formerly Booz & Company" },
    { name: "sustainablebrands.com" },
    { name: "Sydney Morning Herald" },
    { name: "Tactical Investor" },
    { name: "Tech Times" },
    { name: "Technavio" },
    { name: "TeleTrade" },
    { name: "The American Prospect" },
    { name: "The Arab Gulf States Institute Washington" },
    { name: "The Atlantic" },
    { name: "The Chirographer" },
    { name: "The Conversation" },
    { name: "The Economist" },
    { name: "The Engineer" },
    { name: "The Globe and Mail" },
    { name: "The Guardian" },
    { name: "The Independent" },
    { name: "The Jakarta Post" },
    { name: "The Jamestown Foundation" },
    { name: "THE LEAGUE OF WOMEN VOTERS® OF THE FAIRFAX AREA" },
    { name: "The Mainichi" },
    { name: "The Market Mogul" },
    { name: "The Nation" },
    { name: "The Next Web" },
    { name: "the star online" },
    { name: "The Ticker Tape" },
    { name: "TheCable" },
    { name: "theicct" },
    { name: "TheNews.NG" },
    { name: "therobotreport" },
    { name: "thespanisheconomy" },
    { name: "Think Progress" },
    { name: "THISDAY LIVE" },
    { name: "Thomson Reuters " },
    { name: "Time" },
    { name: "Total" },
    { name: "TRAC News" },
    { name: "Transport Environment" },
    { name: "Transport Evolved" },
    { name: "Triple Pundit" },
    { name: "U.K. Ministry of Defense" },
    { name: "U.S. Environmental Protection Agency" },
    { name: "UK Government" },
    { name: "UNEP" },
    { name: "UNESCO " },
    { name: "unian" },
    { name: "University Chronicle" },
    { name: "University of Chicago" },
    { name: "University of Latvia" },
    { name: "uschamber" },
    { name: "USDA" },
    { name: "Utility Dive" },
    { name: "valburyresearch" },
    { name: "Vanguard News" },
    { name: "Verisk Maplecroft" },
    { name: "veteranstoday" },
    { name: "Virgin Atlantic" },
    { name: "VITA Technologies" },
    { name: "VOA" },
    { name: "Vox" },
    { name: "Wall Street Daily" },
    { name: "War on the Rocks" },
    { name: "Washington Post" },
    { name: "watercanada" },
    { name: "Wells Fargo" },
    { name: "westpandi" },
    { name: "Wharton" },
    { name: "What's Next" },
    { name: "Wikipedia" },
    { name: "Wired UK" },
    { name: "Wood McKenzie" },
    { name: "World Bank" },
    { name: "World Bank Group" },
    { name: "World Energy News" },
    { name: "World Health" },
    { name: "worldculturepictorial" },
    { name: "worldenergy" },
    { name: "Worldly" },
    { name: "WSJ" },
    { name: "www.narendramodi.in" },
    { name: "Yahoo Finance" },
    { name: "Yahoo Finance Canada" },
    { name: "Yes Bank" },
    { name: "Zawya" },
    { name: "Zero Hedge" },
]

export const CountryList = [
    { country: "Algeria ", value: "algeria" },
    { country: "Angola ", value: "angola" },
    { country: "Argentina ", value: "argentina" },
    { country: "Australia ", value: "australia" },
    { country: "Austria ", value: "austria" },
    { country: "Azerbaijan ", value: "azerbaijan" },
    { country: "Belize ", value: "belize" },
    { country: "Brazil ", value: "brazil" },
    { country: "Burkina Faso ", value: "burkina faso" },
    { country: "Canada ", value: "canada" },
    { country: "China ", value: "china" },
    { country: "Colombia ", value: "colombia" },
    { country: "Cyprus ", value: "cyprus" },
    { country: "Denmark ", value: "denmark" },
    { country: "Egypt ", value: "egypt" },
    { country: "Estonia ", value: "estonia" },
    { country: "Ethiopia ", value: "ethiopia" },
    { country: "Gabon ", value: "gabon" },
    { country: "Germany ", value: "germany" },
    { country: "Ghana ", value: "ghana" },
    { country: "Greece ", value: "greece" },
    { country: "Hungary ", value: "hungary" },
    { country: "India ", value: "india" },
    { country: "Indonesia ", value: "indonesia" },
    { country: "Iran ", value: "iran" },
    { country: "Iraq ", value: "iraq" },
    { country: "Japan ", value: "japan" },
    { country: "Jordan ", value: "jordan" },
    { country: "Kazakhstan ", value: "kazakhstan" },
    { country: "Kuwait ", value: "kuwait" },
    { country: "Lebanon ", value: "lebanon" },
    { country: "Liberia ", value: "liberia" },
    { country: "Libya ", value: "libya" },
    { country: "Malaysia ", value: "malaysia" },
    { country: "Mali ", value: "mali" },
    { country: "Mexico ", value: "mexico" },
    { country: "Morocco ", value: "morocco" },
    { country: "Niger ", value: "niger" },
    { country: "Nigeria ", value: "nigeria" },
    { country: "Norway ", value: "norway" },
    { country: "Oman ", value: "oman" },
    { country: "Pakistan ", value: "pakistan" },
    { country: "Poland ", value: "poland" },
    { country: "Qatar ", value: "qatar" },
    { country: "Russia ", value: "russia" },
    { country: "Saudi Arabia ", value: "saudi arabia" },
    { country: "South Africa ", value: "south africa" },
    { country: "South Sudan ", value: "south sudan" },
    { country: "Spain ", value: "spain" },
    { country: "Syria ", value: "syria" },
    { country: "Turkey ", value: "turkey" },
    { country: "Ukraine ", value: "ukraine" },
    { country: "United Arab Emirates ", value: "united arab emirates" },
    { country: "United Kingdom ", value: "united kingdom" },
    { country: "United States of America ", value: "united states of america" },
    { country: "Venezuela ", value: "venezuela" },
]



